[package]
name = "tokenizers-el"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.95"
emacs = "0.19.0"
tokenizers = { version = "0.21.0", features = ["http"] }
